### ISSUE TITLE
3.3.5 is not lastest but next

### ISSUE THREAD

**Issue by jcesarmobile** [isaacs/minipass#42]
Not sure if it was a mistake or if it was done on purpose, but 3.3.5 has been published on npm with "next" tag instead of "latest" tag.

I don't use minipass directly, but I'm facing the types issue that has been fixed in 3.3.5 because of dependencies using minipass and my dependencies won't use 3.3.5 because it's not latest.

**Comment by mwturner611** [comment]
I'm still having type issues as well.  I had to track down the 3.3.5 version directly from this repo instead of letting the default npm install from npmjs.com.

**Comment by jimlindeman** [comment]
FYI, I've found 3.3.5 has the same typescript 3.x incompability issue that you fixed great with: https://github.com/isaacs/minipass/commit/08750150d9faebbdb1925719476d67fb5c8f2f13

```
> tsc 
node_modules/minipass/index.d.ts:111:22 - error TS1005: ',' expected.

111       ? [] | [options: Minipass.Options<RType>]
                         ~

node_modules/minipass/index.d.ts:112:17 - error TS1005: ',' expected.

112       : [options: Minipass.Options<RType>]
                 ~
```

The 3.3.4 still build fine with tsc 3.9.10 that I'm using.

**Comment by mhemrg** [comment]
Same issue here with 3.3.5.

**Comment by jcesarmobile** [comment]
This issue is about the npm tag, for the typescript problem, please, create a new issue.

**Comment by fisherking** [comment]
@isaacs could you please release 3.3.5 as the latest version?
